### PR TITLE
Fix file declaration as extensions or names.

### LINKED ISSUE #424: [Task] Review and fix files declaration
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?

Currently, some file declarations are incorrect. (i.e. `.editorconfig` is a configuration file with no extension, and has been declared as a file extension).

**Task assignment:**
Go through all entries in `supportedExtensions.js` and correct the file declaration.

### PR DESCRIPTION
**Pull request by JimiC**
***Fixes #424***

**Changes proposed:**
* [x] Fix

**Things I've done:**
* [x] I've pulled the latest master branch.
* [x] I've run `npm install` to install all the dependencies.
* [x] I've run ESLint.
* [x] My pull request fixes an issue, I referenced the issue.
* [x] I've run `npm run build` to build the extension.

### CODE REVIEW

**Comment by JimiC** [comment]
**Don't merge it yet**
This is a first draft of the changes.

Please review for any mistakes.

File: src/build/supportedExtensions.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ exports.extensions = {
   supported: [
     { icon: 'actionscript', extensions: ['as'] },
     { icon: 'angular', extensions: ['angular-cli.json'], contribType: ctype.filename },
-    { icon: 'apache', extensions: ['htaccess', 'htpasswd'] },
+    { icon: 'apache', extensions: ['htaccess', 'htpasswd'], contribType: ctype.filename },
```
Comment (robertohuertasm) [inline src/build/supportedExtensions.js]: @JimiC note that when stating that some extensions is a filename it must be literal. So in this case, you should change `htacccess` to `.htaccess`.

This worked because when it's considered an extension you ommit the initial dot because it's implicit.

File: src/build/supportedExtensions.js [hunk 2]
```diff
@@ -13,10 +13,10 @@ exports.extensions = {
     { icon: 'aspx', extensions: ['aspx', 'ascx'] },
     { icon: 'assembly', extensions: ['s', 'asm'] },
     { icon: 'autohotkey', extensions: ['ahk'] },
-    { icon: 'babel', extensions: ['babelrc'] },
+    { icon: 'babel', extensions: ['babelrc'], contribType: ctype.filename },
```
Comment (robertohuertasm) [inline src/build/supportedExtensions.js]: Same here. The initial dot is missing.

File: src/build/supportedExtensions.js (hunk 1 above)
Comment (JimiC) [inline src/build/supportedExtensions.js]: Sure thing.

File: src/build/supportedExtensions.js (hunk 2 above)
Comment (JimiC) [inline src/build/supportedExtensions.js]: Sure thing. I'll scan for additional cases.

**Comment by JimiC** [comment]
@robertohuertasm @madskristensen Mads has a nice list with file extensions we could use as reference.

**Comment by robertohuertasm** [comment]
@JimiC that's ok for me. We're adding icons on demand at the moment so having a pre-built list so we can see if something is missing it's always nice.

**Comment by JimiC** [comment]
@robertohuertasm I just realized that `.nuget` extension is declared as a file when it's actually a folder. I'll move the declaration to the `supportedFolders` and create and add an appropriate icon. Objections?

**Comment by robertohuertasm** [comment]
@JimiC none. All yours!

**Comment by JimiC** [comment]
**Don't merge it yet**
This is a second draft of the changes.

Please review for any mistakes.

File: src/build/supportedExtensions.js [hunk 3]
```diff
@@ -32,42 +30,36 @@ exports.extensions = {
...
-    { icon: 'eslint', extensions: ['.eslintrc.yaml'], contribType: ctype.filename },
-    { icon: 'eslint', extensions: ['.eslintrc.yml'], contribType: ctype.filename },
+    { icon: 'erlang', extensions: ['erl', 'hrl'] },
+    { icon: 'erlang', extensions: ['emakefile', '.emakerfile'], contribType: ctype.filename },
+    { icon: 'eslint', extensions: ['.eslintrc', '.eslintignore', '.eslintrc.js', '.eslintrc.json', '.eslintrc.yaml', '.eslintrc.yml'], contribType: ctype.filename },
     { icon: 'excel', extensions: ['xls', 'xlsx', 'csv', 'ods'] },
     { icon: 'favicon', extensions: ['favicon.ico'], contribType: ctype.filename },
     { icon: 'flash', extensions: ['swf', 'swc', 'sol'] },
-    { icon: 'flow', extensions: ['flowconfig', 'js.flow'] },
+    { icon: 'flow', extensions: ['.flowconfig', 'js.flow'], contribType: ctype.filename },
```
Comment (robertohuertasm) [inline src/build/supportedExtensions.js]: `js.flow` it's a complex extension. At least I guess so. I'm not a flow user at all. I think it should be in a separate entry.

File: src/build/supportedExtensions.js [hunk 4]
```diff
@@ -87,24 +79,21 @@ exports.extensions = {
...
-    { icon: 'jade', extensions: ['.pug-lintrc.js'], contribType: ctype.filename },
-    { icon: 'jade', extensions: ['.pug-lintrc.json'], contribType: ctype.filename },
+    { icon: 'jade', extensions: ['jade', 'pug', 'tag'] },
+    { icon: 'jade', extensions: ['.jade-lintrc', '.pug-lintrc', '.jade-lint.json', '.pug-lintrc.js', '.pug-lintrc.json'], contribType: ctype.filename },
     { icon: 'java', extensions: ['java'] },
     { icon: 'jbuilder', extensions: ['jbuilder'], svg: true },
     { icon: 'jinja', extensions: ['jinja'] },
     { icon: 'js', extensions: ['js'] },
-    { icon: 'jshintrc', extensions: ['jshintrc'] },
+    { icon: 'jshintrc', extensions: ['jshintrc'], contribType: ctype.filename },
```
Comment (robertohuertasm) [inline src/build/supportedExtensions.js]: a dot is missing: `.jshintrc`

Comment (JimiC) [inline src/build/supportedExtensions.js]: Good catch.

**Comment by JimiC** [comment]
I have removed the `contribOrder` and done the merging also in my commit. Maybe one of us should do this to avoid conflicts.

**Comment by robertohuertasm** [comment]
@JimiC don't worry. I was preparing another branch with this but I will merge yours.

File: src/build/supportedExtensions.js (hunk 3 above)
Comment (JimiC) [inline src/build/supportedExtensions.js]: Indeed `js.flow` is a file extension. Good catch.

Comment (robertohuertasm) [inline src/build/supportedExtensions.js]: special ones must be `.js.flow` no contribtype

Comment (JimiC) [inline src/build/supportedExtensions.js]: Like `blade`! I see. Gotcha.

Comment (robertohuertasm) [inline src/build/supportedExtensions.js]: Yes, but I'm thinking now that this is also a legacy convention that could be removed. Let me test it before removing this.

Comment (robertohuertasm) [inline src/build/supportedExtensions.js]: Yes, you can ignore the initial dot in complex extensions.

Comment (robertohuertasm) [inline src/build/supportedExtensions.js]: Yes, indeed. If you don't do it I'll do it! 😉

Comment (JimiC) [inline src/build/supportedExtensions.js]: Already done it.

**Comment by JimiC** [comment]
Third draft.

Inspect.

**Comment by JimiC** [comment]
That was fun. Nice collaboration. :metal:

**Comment by JimiC** [comment]
I indeed missed the `.nvmrc` file.
On another note `dockerfile` isn't an extension. Don't change it in the declaration.

**Comment by robertohuertasm** [comment]
Thank you very much @JimiC! You're very welcome to collaborate whenever you want! This is your home! 😉

**Comment by robertohuertasm** [comment]
I modified .nvrmc to filename and let dockerfile as an extension because some people like to add it some stuff and use it as an extension just for different purposes.

**Comment by JimiC** [comment]
I see. I'm fine with that.

**Comment by robertohuertasm** [comment]
Dockerfile is treated as a filename and also as a extension, that's what I meant. (although I know it's a filename)

**Comment by robertohuertasm** [comment]
This should be live tomorrow. You're in the changelog!

**Comment by JimiC** [comment]
I know. I'm reading as we speak. :smile:

Don't you want to wait till I convert the icons to SVG or we can do that on next iteration?

**Comment by robertohuertasm** [comment]
Let's roll this up as this is a major change from v3 to v4 (no support for custom code injection in <1.6.0) and let's deploy your svg changes in another iteration if that's fine for you.

**Comment by JimiC** [comment]
OK, sure. I probably have them ready on next weekend. (Kinda mad busy with work on the weekdays).

**Comment by robertohuertasm** [comment]
No rush. I use to also do things on this repo on weekends :wink: Thanks again @jimic!

**Comment by JimiC** [comment]
@robertohuertasm Was a pleasure.
